### ISSUE TITLE
Automatic daylight savings ajustment

### ISSUE THREAD

**Issue by cculpepper** [carrotIndustries/pluto-fw#5]
Would it be possible to utilize one of the other RTCs on the chip to set an alarm to activate on the day of the next daylight savings change, and to automatically add or subtract the hour?

Looking at the users guide for the chip, it has 3 RTCs, which support alarms for day of the month only. The service routine would get called every month, and a simple month check can be performed, update performed, and the alarm updated. 

I am just getting familiar with this chip and the framework so am wondering if this is feasible / if there is an easier way

**Comment by carrotIndustries** [comment]
The MSP430FR6972 has many timers but only _one_ RTC. I've though of some ways for adjusting the RTC without interrupting the RTC too much, i.e. a menu itemfor  incrementing/decrementing the RTC in 30/60 min steps. (<- preferred solution, since this keeps complexity low)

Not sure if there's some sensible way of dealing with timezones/daylight saving with the RTC running in local time. I'd like to avoid having the RTC set to UTC, since calculating the local time from UTC is very like to significantly increase power consumption.

Also keep https://xkcd.com/1205/ in mind. Let's say adjusting the time twice a year using the aforementioned 30min steps takes 30 sec each time. According to this xkcd, you can work on automatic daylight saving for 5 min tops. Answering this issue already took me that long.

**Comment by carrotIndustries** [comment]
417d7434f651dc885c8348bdbcbcae10387e3933 also got us a way of adjusting the time by +/-1h keeping the seconds mostly correct
